{
 "title": "Smart Home ",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Dooz Buzzer (DB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"smarthome\")\r\n  |> range(start: -30m)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"door_buzzer\" and\r\n    r._field == \"value\"\r\n  )\r\n"
    }
   ]
  },
  {
   "title": "Door Light (DL)",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"smarthome\")\r\n  |> range(start: -60m)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"door_light\" and\r\n    r._field == \"value\"\r\n  )\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n"
    }
   ]
  },
  {
   "title": "Door Membrane Switch (DMS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"smarthome\")\r\n  |> range(start: -60m)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"door_membrane_switch\" and\r\n    r._field == \"key\"\r\n  )\r\n"
    }
   ]
  },
  {
   "title": "Door State Sensor (DS1)",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"smarthome\")\r\n  |> range(start: -30m)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"door_sensor\" and\r\n    r._field == \"value\"\r\n  )\r\n\r\n"
    }
   ]
  },
  {
   "title": "Door Motion Sensor (DPIR1)",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "query": "from(bucket: \"smarthome\")\r\n  |> range(start: -30m)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"door_motion_sensor\" and\r\n    r._field == \"value\"\r\n  )\r\n"
    }
   ]
  },
  {
   "title": "Door Distance Sensor (DUS1)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "query": "from(bucket: \"smarthome\")\r\n  |> range(start: -30m)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"ultrasonic_sensor\" and\r\n    r._field == \"distance\"\r\n  )"
    }
   ]
  }
 ]
}